workflows:
  android-apk-build:
    name: Build Android APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build Android APK
        script: |
          find . -name "gradlew" -exec chmod +x {} \;
          find . -name "gradlew" -execdir ./gradlew assembleDebug \;
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
